In [1]:
print("hello")

hello

In [3]:
import pandas as pd
import numpy as np

### Import Tables

In [5]:
orders= pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Orders.csv")
order_items = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/OrderItems.csv")
products = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Products.csv")
products_category = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/ProductCategory.csv")
customers = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Customers.csv")
sellers = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Sellers.csv")
payments = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Payments.csv")
reviews = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/OrderReviews.csv")
geolocation = pd.read_csv("/home/user/Suraj/Work/E_Commerce/Raw/Geolocation.csv")

#### __orders__:
- __order_id__: unique identifier of order
- __order_status__: delivered, canceled, etc
- __order_purchase_timestamp__: when order was placed
- __order_approved_at__: when order was approved
- __order_delivered_carrier_date__: date when the order is handed over to the carrier for shipment
- __order_delivered_customer_date__: actual date the order is delivered to the customer
- __order_estimated_delivery_date__: predicted date by which the customer is expected to receive the order
#### __order_items__:
- __order_id__: Unique identifier linking all items in a single order
- __order_item_id__: Sequential number identifying each item within the same order (e.g., first item, second item)
- __product_id__: Unique identifier of the product sold
- __seller_id__: Unique identifier of the seller fulfilling the item
- __shipping_limit_date__: Deadline by which the seller must hand over the item to the logistics partner
- __price__: Final sale price of the individual item
- __freight_value__: Shipping cost attributed to the item (shared across items if multiple in one order)

#### __products__:
- __product_id__: Unique identifier for the product
- __product_category_name__: Category to which the product belongs (e.g., electronics, furniture)
- __product_name_lenght__: Number of characters in the product's name
- __product_description_lenght__: Number of characters in the product's description
- __product_photos_qty__: Number of images associated with the product
- __product_weight_g__: Weight of the product in grams
- __product_length_cm__: Length of the product in centimeters
- __product_height_cm__: Height of the product in centimeters
- __product_width_cm__: Width of the product in centimeters 

#### __products_category__:
- __product_category_name__: Category name in Portuguese (original language of the dataset)
- __product_category_name_english__: English translation of the product category name


#### __customers__:
- __customer_id__: Identifier for a specific order transaction; the same customer can have multiple customer_ids across different orders
- __customer_unique_id__: Unique identifier for a customer across all orders; used to identify and track individual customers
- __customer_zip_code_prefix__: First 5 digits of the customer’s postal code
- __customer_city__: City where the customer is located
- __customer_state__: State where the customer is located

#### __sellers__:
- __seller_id__: Unique identifier for the seller
- __seller_zip_code_prefix__: First 5 digits of the seller’s postal code
- __seller_city__: City where the seller is located
- __seller_state__: State where the seller is located

#### __payments__:
- __order_id__: Unique identifier for the order
- __payment_sequential__: Sequence number for multiple payment methods used in a single order (e.g., 1st, 2nd payment)
- __payment_type__: Method of payment (e.g., credit card, debit card)
- __payment_installments__: Number of installments selected for the payment (e.g., 1 = full payment, 3 = split into 3 payments)
- __payment_value__: Transaction amount for that specific payment

#### __reviews__:
- __review_id__: Unique identifier for the customer review
- __order_id__: Identifier linking the review to a specific order
- __review_score__: Rating given by the customer, from 1 (lowest) to 5 (highest)
- __review_comment_title__: Short headline summarizing the review
- __review_comment_message__: Detailed feedback or comment provided by the customer
- __review_creation_date__: Timestamp when the review was written by the customer
- __review_answer_timestamp__: Timestamp when the seller or marketplace responded to the review

#### __geolocation__:
- __geolocation_zip_code_prefix__: First few digits of the postal code used for geographic identification
- __geolocation_lat__: Latitude coordinate of the zip code area
- __geolocation_lng__: Longitude coordinate of the zip code area
- __geolocation_city__: City corresponding to the zip code
- __geolocation_state__: State corresponding to the zip code

### Orders

In [6]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [7]:
orders["order_purchase_timestamp"]= pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_approved_at"] = pd.to_datetime(orders["order_approved_at"])
orders["order_delivered_carrier_date"] = pd.to_datetime(orders["order_delivered_carrier_date"])
orders["order_delivered_customer_date"] = pd.to_datetime(orders["order_delivered_customer_date"])
orders["order_estimated_delivery_date"] = pd.to_datetime(orders["order_estimated_delivery_date"])

In [8]:
orders.shape

(99441, 8)

In [9]:
orders.drop_duplicates()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### Order_items

In [11]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [12]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])
order_items.drop_duplicates
print(order_items.shape)

(112650, 7)

In [13]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [14]:
order_items[order_items["price"]<0]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [15]:
order_items[order_items["freight_value"]<0]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

### Payments

In [16]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [17]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [18]:
payments[payments["payment_value"]<0]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [19]:
payments.drop_duplicates

<bound method DataFrame.drop_duplicates of                                 order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
...                                  ...                 ...          ...
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
0                          8          99.33
1                          1          24.39
2                          1          65.71
3                          8         107.78
4                          2         128.45
...                      ...            ...
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58

[103886 rows x 5 columns]>

### Reviews

In [20]:
reviews.shape

(99224, 7)

In [21]:
reviews.drop_duplicates

<bound method DataFrame.drop_duplicates of                               review_id                          order_id  \
0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
...                                 ...                               ...
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

       review_score review_comment_title  \
0                 4                  NaN
1                 5                  NaN
2                 5                  NaN
3                 5                  NaN
4                 5                  NaN
...             ...                  ...
99219             5                  NaN
99220             5                  NaN
99221             5                  NaN
99222             4                  NaN
99223             1                  NaN

                                  review_comment_message review_creation_date  \
0                                                    NaN  2018-01-18 00:00:00
1                                                    NaN  2018-03-10 00:00:00
2                                                    NaN  2018-02-17 00:00:00
3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00
...                                                  ...                  ...
99219                                                NaN  2018-07-07 00:00:00
99220                                                NaN  2017-12-09 00:00:00
99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
99222                                                NaN  2018-07-01 00:00:00
99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

      review_answer_timestamp
0         2018-01-18 21:46:59
1         2018-03-11 03:05:13
2         2018-02-18 14:36:24
3         2017-04-21 22:02:06
4         2018-03-02 10:26:53
...                       ...
99219     2018-07-14 17:18:30
99220     2017-12-11 20:06:42
99221     2018-03-23 09:10:43
99222     2018-07-02 12:59:13
99223     2017-07-03 21:01:49

[99224 rows x 7 columns]>

In [22]:
reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [23]:
reviews["review_creation_date"]= pd.to_datetime(reviews["review_creation_date"], errors='coerce')
reviews["review_answer_timestamp"]= pd.to_datetime(reviews["review_answer_timestamp"])

In [24]:
reviews[reviews["review_score"]<0]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [25]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [26]:
reviews_agg = (
    reviews
    .groupby('order_id', as_index=False)
    .agg(avg_review_score=('review_score', 'mean'))
)

### Products

In [27]:
products.drop_duplicates

<bound method DataFrame.drop_duplicates of                              product_id              product_category_name  \
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
0                     40.0                       287.0                 1.0
1                     44.0                       276.0                 1.0
2                     46.0                       250.0                 1.0
3                     27.0                       261.0                 1.0
4                     37.0                       402.0                 4.0
...                    ...                         ...                 ...
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
0                 225.0               16.0               10.0
1                1000.0               30.0               18.0
2                 154.0               18.0                9.0
3                 371.0               26.0                4.0
4                 625.0               20.0               17.0
...                 ...                ...                ...
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
0                  14.0
1                  20.0
2                  15.0
3                  26.0
4                  13.0
...                 ...
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

[32951 rows x 9 columns]>

In [28]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [29]:
products['product_category_name'] = products['product_category_name'].fillna('unknown')

In [30]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

### Sellers

In [31]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [32]:
sellers.drop_duplicates

<bound method DataFrame.drop_duplicates of                              seller_id  seller_zip_code_prefix  \
0     3442f8959a84dea7ee197c632cb2df15                   13023
1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
...                                ...                     ...
3090  98dddbc4601dd4443ca174359b237166                   87111
3091  f8201cab383e484733266d1906e2fdfa                   88137
3092  74871d19219c7d518d0090283e03c137                    4650
3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
3094  9e25199f6ef7e7c347120ff175652c3b                   12051

            seller_city seller_state
0              campinas           SP
1            mogi guacu           SP
2        rio de janeiro           RJ
3             sao paulo           SP
4     braganca paulista           SP
...                 ...          ...
3090            sarandi           PR
3091            palhoca           SC
3092          sao paulo           SP
3093            pelotas           RS
3094            taubate           SP

[3095 rows x 4 columns]>

In [33]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [35]:
orders.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/orders.csv")
products.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/products.csv")
products_category.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/products_category.csv")
customers.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/customers.csv")
sellers.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/sellers.csv")
reviews.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/reviews.csv")
order_items.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/order_items.csv")
payments.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/payments.csv")

In [36]:
order_details_agg = ( 
    order_items.groupby('order_id')
        .agg( order_value = ('price','sum'),
              total_freight_value = ('freight_value','sum'),
              item_count=('order_item_id','count')
            ).reset_index())

In [37]:
order_details_agg

,order_id,order_value,total_freight_value,item_count
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,1
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,1
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,1
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,1
...,...,...,...,...
98661,fffc94f6ce00a00581880bf54a75a037,299.99,43.41,1
98662,fffcd46ef2263f404302a634eb57f7eb,350.00,36.53,1
98663,fffce4705a9662cd70adb13d4a31832d,99.90,16.95,1
98664,fffe18544ffabc95dfada21779c9644f,55.99,8.72,1
98665,fffe41c64501cc87c801fd61db3f6244,43.00,12.79,1

In [38]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [39]:
payment_agg = (
    payments.groupby('order_id')
        .agg( total_payment_value =('payment_value','sum'),
              payment_installments=('payment_installments','max'),
              payment_type=('payment_type',lambda x:x.mode()[0])
            ).reset_index()
)

In [40]:
payment_agg

,order_id,total_payment_value,payment_installments,payment_type
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,credit_card
...,...,...,...,...
99435,fffc94f6ce00a00581880bf54a75a037,343.40,1,boleto
99436,fffcd46ef2263f404302a634eb57f7eb,386.53,1,boleto
99437,fffce4705a9662cd70adb13d4a31832d,116.85,3,credit_card
99438,fffe18544ffabc95dfada21779c9644f,64.71,3,credit_card
99439,fffe41c64501cc87c801fd61db3f6244,55.79,1,credit_card

In [41]:
reviews_clean = reviews[['order_id','review_score','review_creation_date']]

In [42]:
reviews_clean

                               order_id  review_score review_creation_date
0      73fc7af87114b39712e6da79b0a377eb             4           2018-01-18
1      a548910a1c6147796b98fdf73dbeba33             5           2018-03-10
2      f9e4b658b201a9f2ecdecbb34bed034b             5           2018-02-17
3      658677c97b385a9be170737859d3511b             5           2017-04-21
4      8e6bfb81e283fa7e4f11123a3fb894f1             5           2018-03-01
...                                 ...           ...                  ...
99219  2a8c23fee101d4d5662fa670396eb8da             5           2018-07-07
99220  22ec9f0669f784db00fa86d035cf8602             5           2017-12-09
99221  55d4004744368f5571d1f590031933e4             5           2018-03-22
99222  7725825d039fc1f0ceb7635e3f7d9206             4           2018-07-01
99223  90531360ecb1eec2a1fbb265a0db0508             1           2017-07-03

[99224 rows x 3 columns]

In [43]:
orders['delivery_time_days']=(orders['order_delivered_customer_date']-orders['order_purchase_timestamp']).dt.days
orders['delivery_delay_days']=(orders['order_delivered_customer_date']-orders['order_estimated_delivery_date']).dt.days
orders['is_delayed']=orders['delivery_delay_days']>0

In [44]:
order_level = (orders
    .merge(order_details_agg,on='order_id',how='left')
    .merge(payment_agg,on='order_id',how='left')
    .merge(reviews_clean,on='order_id',how='left')          
    )

In [45]:
order_level.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99992 entries, 0 to 99991
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99992 non-null  object
 1   customer_id                    99992 non-null  object
 2   order_status                   99992 non-null  object
 3   order_purchase_timestamp       99992 non-null  datetime64[ns]
 4   order_approved_at              99831 non-null  datetime64[ns]
 5   order_delivered_carrier_date   98199 non-null  datetime64[ns]
 6   order_delivered_customer_date  97005 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99992 non-null  datetime64[ns]
 8   delivery_time_days             97005 non-null  float64
 9   delivery_delay_days            97005 non-null  float64
 10  is_delayed                     99992 non-null  bool
 11  order_value                    99214 non-null  float64
 12  total_freight_value            99214 non-null  float64
 13  item_count                     99214 non-null  float64
 14  total_payment_value            99991 non-null  float64
 15  payment_installments           99991 non-null  float64
 16  payment_type                   99991 non-null  object
 17  review_score                   99224 non-null  float64
 18  review_creation_date           99224 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](6), float64(8), object(4)
memory usage: 13.8+ MB

In [46]:
import pandas as pd

# join customers → orders
cust_orders = orders.merge(
    customers[['customer_id', 'customer_unique_id']],
    on='customer_id',
    how='left'
)

# join order_level
cust_orders = cust_orders.merge(
    order_level[['order_id', 'order_value']],
    on='order_id',
    how='left'
)

# join reviews
cust_orders = cust_orders.merge(
    reviews_agg,
    on='order_id',
    how='left'
)

In [47]:
print(cust_orders.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_time_days', 'delivery_delay_days', 'is_delayed',
       'customer_unique_id', 'order_value', 'avg_review_score'],
      dtype='object')

In [61]:
customer_level = (
    cust_orders
    .groupby('customer_unique_id')
    .agg(
        first_purchase_date=('order_purchase_timestamp', 'min'),
        last_purchase_date=('order_purchase_timestamp', 'max'),
        total_orders=('order_id', 'nunique'),
        total_revenue=('order_value', 'sum'),
        avg_delivery_delay=('delivery_delay_days', 'mean')
    )
    .reset_index()
)

order_level = order_level.merge(
    customers[['customer_id', 'customer_unique_id']],
    on='customer_id',
    how='left'
)

In [62]:
customer_level

,customer_unique_id,first_purchase_date,last_purchase_date,total_orders,total_revenue,avg_delivery_delay
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,2018-05-10 10:56:27,1,129.90,-5.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,2018-05-07 11:11:27,1,18.90,-5.0
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,2017-03-10 21:05:03,1,69.00,-2.0
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,2017-10-12 20:29:41,1,25.99,-12.0
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,2017-11-14 19:45:42,1,180.00,-8.0
...,...,...,...,...,...,...
96091,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,2017-06-08 21:00:36,1,1570.00,-27.0
96092,fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,2017-12-10 20:07:56,1,64.89,-3.0
96093,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,2017-02-07 15:49:16,1,89.90,-30.0
96094,ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,2018-05-02 15:17:41,1,115.00,-14.0
96095,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,2017-05-02 20:18:45,1,56.99,-16.0

In [63]:
seller_level = (
    order_items
    .groupby('seller_id')
    .agg(
        total_orders=('order_id','nunique'),
        total_revenue=('price','sum')
        ).reset_index()
    )

In [64]:
order_level = order_level.copy()

order_level = order_level.drop_duplicates(subset=['order_id'])

seller_order = (
    order_items
    .groupby(['order_id', 'seller_id'], as_index=False)
    .agg(
        item_count=('order_item_id', 'count'),
        seller_order_revenue=('price', 'sum'),
        seller_freight_revenue=('freight_value', 'sum')
    )
)

seller_order['seller_order_revenue'] = (
    seller_order['seller_order_revenue'] +
    seller_order['seller_freight_revenue']
)


seller_order = seller_order.merge(
    order_level[['order_id', 'is_delayed', 'delivery_delay_days', 'review_score']],
    on='order_id',
    how='left'
)

seller_level = (
    seller_order
    .groupby('seller_id', as_index=False)
    .agg(
        total_orders=('order_id', 'nunique'),
        total_revenue=('seller_order_revenue', 'sum'),
        delayed_orders=('is_delayed', lambda x: (x == True).sum()),
        avg_delivery_delay=('delivery_delay_days', 'mean'),
        avg_review_score=('review_score', 'mean'),
        one_star_pct=('review_score', lambda x: (x == 1).mean() * 100)
    )
)

seller_level['delay_pct'] = (
    seller_level['delayed_orders'] /
    seller_level['total_orders'] * 100
)

In [65]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [66]:
seller_level

,seller_id,total_orders,total_revenue,delayed_orders,avg_delivery_delay,avg_review_score,one_star_pct,delay_pct
0,0015a82c2db000af6aaaf3ae2ecb0532,3,2748.06,0,-16.333333,3.666667,33.333333,0.000000
1,001cca7ae9ae17fb1caed9dfb1094831,200,33934.17,12,-12.882051,3.984772,12.000000,6.000000
2,001e6ad469a905060d959994f1b41e4f,1,267.94,0,NaN,1.000000,100.000000,0.000000
3,002100f778ceb8431b7a1020ff7ab48f,51,2028.16,9,-8.180000,3.901961,13.725490,17.647059
4,003554e2dce176b5555353e4f3555ac8,1,139.38,0,-27.000000,5.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
3090,ffcfefa19b08742c5d315f2791395ee5,1,79.52,0,NaN,1.000000,100.000000,0.000000
3091,ffdd9f82b9a447f6f8d4b91554cc7dd3,18,2828.66,0,-12.388889,4.333333,5.555556,0.000000
3092,ffeee66ac5d5a62fe688b9d26f83f534,14,2259.55,2,-8.357143,4.214286,14.285714,14.285714
3093,fffd5413c0700ac820c7069d66d98c89,60,11896.04,7,-11.228070,3.847458,18.333333,11.666667
3094,ffff564a4f9085cd26170f4732393726,20,1770.86,0,-48.000000,2.100000,65.000000,0.000000

In [67]:
customer_level

,customer_unique_id,first_purchase_date,last_purchase_date,total_orders,total_revenue,avg_delivery_delay
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,2018-05-10 10:56:27,1,129.90,-5.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,2018-05-07 11:11:27,1,18.90,-5.0
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,2017-03-10 21:05:03,1,69.00,-2.0
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,2017-10-12 20:29:41,1,25.99,-12.0
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,2017-11-14 19:45:42,1,180.00,-8.0
...,...,...,...,...,...,...
96091,fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,2017-06-08 21:00:36,1,1570.00,-27.0
96092,fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,2017-12-10 20:07:56,1,64.89,-3.0
96093,ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,2017-02-07 15:49:16,1,89.90,-30.0
96094,ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,2018-05-02 15:17:41,1,115.00,-14.0
96095,ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,2017-05-02 20:18:45,1,56.99,-16.0

In [68]:
order_level

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,delivery_delay_days,...,order_value,total_freight_value,item_count,total_payment_value,payment_installments,payment_type,review_score,review_creation_date,customer_unique_id_x,customer_unique_id_y
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8.0,-8.0,...,29.99,8.72,1.0,38.71,1.0,voucher,4.0,2017-10-11,7c396fd4830fd04220f754e42b4e5bff,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13.0,-6.0,...,118.70,22.76,1.0,141.46,1.0,boleto,4.0,2018-08-08,af07308b275d755c9edb36a90c618231,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9.0,-18.0,...,159.90,19.22,1.0,179.12,3.0,credit_card,5.0,2018-08-18,3a653a41f6f9fc3d2a113cf8398680e8,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13.0,-13.0,...,45.00,27.20,1.0,72.20,1.0,credit_card,5.0,2017-12-03,7c142cf63193a1473d2e66489a9ae977,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2.0,-10.0,...,19.90,8.72,1.0,28.62,1.0,credit_card,5.0,2018-02-17,72632f0f9dd73dfee390c9b22eb56dd6,72632f0f9dd73dfee390c9b22eb56dd6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,8.0,-11.0,...,72.00,13.08,1.0,85.08,3.0,credit_card,5.0,2017-03-22,6359f309b166b0196dbf7ad2ac62bb5a,6359f309b166b0196dbf7ad2ac62bb5a
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0,-2.0,...,174.90,20.10,1.0,195.00,3.0,credit_card,4.0,2018-03-01,da62f9e57a76d978d02ab5362c509660,da62f9e57a76d978d02ab5362c509660
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,24.0,-6.0,...,205.99,65.02,1.0,271.01,5.0,credit_card,5.0,2017-09-22,737520a9aad80b3fbbdad19b66b37b30,737520a9aad80b3fbbdad19b66b37b30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0,-21.0,...,359.98,81.18,2.0,441.16,4.0,credit_card,2.0,2018-01-26,5097a5312c8b157bb7be58ae360ef43c,5097a5312c8b157bb7be58ae360ef43c
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,7.0,-18.0,...,68.50,18.36,1.0,86.86,1.0,debit_card,5.0,2018-03-17,60350aa974b26ff12caad89e55993bd6,60350aa974b26ff12caad89e55993bd6

In [69]:
orders['review_score']=reviews['review_score']

In [70]:
# - Which product categories have highest delays?
# - Which products drive revenue vs. problems?
# - Category-specific seller performance
# product_level will help analyse above business problems

product_level = order_items.merge(
    products[['product_id', 'product_category_name']], 
    on='product_id'
).merge(
    orders[['order_id','review_score', 'is_delayed', 'delivery_delay_days']], 
    on='order_id'
).groupby('product_category_name').agg({
    'order_id': 'nunique',                    # total_orders
    'price': 'sum',                            # total_revenue
    'freight_value': 'sum',                    # total_freight
    'is_delayed': 'sum',                       # delayed_orders
    'delivery_delay_days': 'mean',             # avg_delay
    'review_score': 'mean'                     # avg_rating
}).reset_index()

product_level.columns = [
    'product_category', 'total_orders', 'total_revenue', 
    'total_freight', 'delayed_orders', 'avg_delivery_delay', 'avg_review_score'
]

product_level['delay_pct'] = (
    product_level['delayed_orders'] / product_level['total_orders'] * 100
)

product_level['revenue_per_order'] = (
    product_level['total_revenue'] / product_level['total_orders']
)

In [71]:
sum(customer_level['total_revenue'])

13651923.470011706

## Analysis ready tables

In [79]:
order_level.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/ready/order_level.csv")
customer_level.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/ready/customer_level.csv")
seller_level.to_csv("/home/user/Suraj/Work/E_Commerce/Cleaned/ready/seller_level.csv")

# Cleaning and feature engineering done